### ISSUE TITLE
asset.tracks empty

### ISSUE THREAD

**Issue by emilkorngold** [gchilds/MTAudioProcessingTap-in-Swift#3]
Hey there, thanks for sharing this repo publicly. At some point after recent iOS updates, your code is no longer working. The asset tracks array returns an empty array. Do you have the intention to fix this bug sometime in the near future? Best regards, Emil Korngold

**Comment by gchilds** [comment]
Hi - are you talking about a remote asset? Because while the `AVPlayerItem` might eventually load tracks, the underlying `AVAsset` does not and I cannot find any way to make such assets work with an audio tap. Might be worth burning an Apple TSI on.

*N.B.* some remote assets work fine, e.g. an mp3 with a content-length.

**Comment by gchilds** [comment]
Something changed in `AVFoundation` - most remote assets no longer give you non-empty `tracks` arrays. I can't see any way around it, so I've mentioned it in the readme.
